module.exports = [
  {"id": "11", "group": "threefour", "name": "Craig","color": "teal"},
  {"id": "12", "group": "threefour", "name": "Dickson","color": "purple"},
  {"id": "13", "group": "threefour", "name": "Holleman","color": "pink"},
  {"id": "14", "group": "threefour", "name": "McInstosh","color": "maroon"},
  {"id": "15", "group": "threefour", "name": "Miller","color": "orange"},
  {"id": "16", "group": "threefour", "name": "Brandau","color": "forestgreen"},
  {"id": "17", "group": "threefour", "name": "The Rathe's","color": "red"},
  {"id": "18", "group": "threefour", "name": "McGuigan","color": "white"},
  {"id": "19", "group": "threefour", "name": "Corts/Hernandez","color": "green"},
  {"id": "110", "group": "threefour", "name": "Frericks","color": "royalblue"},
  {"id": "111", "group": "threefour", "name": "Lee/Adair","color": "grey"},
  {"id": "112", "group": "threefour", "name": "Schickling/Perry","color": "skyblue"},
  {"id": "113", "group": "threefour", "name": "Stanley","color": "gold"},
  {"id": "114", "group": "threefour", "name": "Amden/Martin","color": "pink"},
  {"id": "115", "group": "threefour", "name": "Willingham","color": "black"},
  {"id": "116", "group": "threefour", "name": "Schirm/Meyer","color": "navy"},
  {"id": "21", "group": "fivek", "name": "Pittman","color": "green"},
  {"id": "22", "group": "fivek", "name": "Frericks","color": "pink"},
  {"id": "23", "group": "fivek", "name": "Calderon","color": "navy"},
  {"id": "24", "group": "fivek", "name": "Larkin","color": "white"},
  {"id": "25", "group": "fivek", "name": "Holleman","color": "orange"},
  {"id": "26", "group": "fivek", "name": "Austin","color": "purple"},
  {"id": "27", "group": "fivek", "name": "Calderon","color": "black"},
  {"id": "28", "group": "fivek", "name": "Dickson","color": "grey"},
  {"id": "29", "group": "fivek", "name": "Fleming","color": "gold"},
  {"id": "210", "group": "fivek", "name": "Nichols","color": "red"},
  {"id": "31",  "group": "firstsecond","name": "King", "color": "red"},
  {"id": "32",  "group": "firstsecond","name": "Gaylon", "color": "pink"},
  {"id": "33",  "group": "firstsecond","name": "McGuire", "color": "royalblue"},
  {"id": "34",  "group": "firstsecond","name": "Bridges", "color": "lightgrey"},
  {"id": "35",  "group": "firstsecond","name": "Welborn", "color": "black"},
  {"id": "36",  "group": "firstsecond","name": "Porter", "color": "pink"},
  {"id": "37",  "group": "firstsecond","name": "Porter", "color": "white"},
  {"id": "38",  "group": "firstsecond","name": "Theobald/Little", "color": "maroon"},
  {"id": "39",  "group": "firstsecond","name": "Cowles", "color": "teal"},
  {"id": "310", "group": "firstsecond", "name": "Holstein", "color": "orange"},
  {"id": "311", "group": "firstsecond", "name": "Cherry", "color": "white"},
  {"id": "312", "group": "firstsecond", "name": "Brock", "color": "skyblue"},
  {"id": "313", "group": "firstsecond", "name": "Schultz", "color": "gold"},
  {"id": "314", "group": "firstsecond", "name": "McEvoy", "color": "purple"},
  {"id": "315", "group": "firstsecond", "name": "Crowell", "color": "forestgreen"},
  {"id": "316", "group": "firstsecond", "name": "Gibbs", "color": "forestgreen"},
  {"id": "317", "group": "firstsecond", "name": "Nickoloff", "color": "royalblue"},
  {"id": "318", "group": "firstsecond", "name": "Frost", "color": "white"},
  {"id": "319", "group": "firstsecond", "name": "Weaver", "color": "navy"},
  {"id": "320", "group": "firstsecond", "name": "Franke", "color": "red"},
  {"id": "321", "group": "firstsecond", "name": "McDaniel", "color": "black"},
  {"id": "41", "group": "thirdfourth", "name": "Johns","color": "skyblue"},
  {"id": "42", "group": "thirdfourth", "name": "Ashworth","color": "teal"},
  {"id": "43", "group": "thirdfourth", "name": "Wrubel","color": "red"},
  {"id": "44", "group": "thirdfourth", "name": "Douglas","color": "navy"},
  {"id": "45", "group": "thirdfourth", "name": "Edwards","color": "pink"},
  {"id": "46", "group": "thirdfourth", "name": "Laufer","color": "white"},
  {"id": "47", "group": "thirdfourth", "name": "Mitchell","color": "forestgreen"},
  {"id": "48", "group": "thirdfourth", "name": "Larkin/Puryear","color": "orange"},
  {"id": "49", "group": "thirdfourth", "name": "Thorton","color": "purple"},
  {"id": "410", "group": "thirdfourth", "name": "Roark/Fitzwater","color": "gold"},
  {"id": "411", "group": "thirdfourth", "name": "Burton","color": "pink"},
  {"id": "412", "group": "thirdfourth", "name": "Baxter","color": "maroon"},
  {"id": "413", "group": "thirdfourth", "name": "Perry","color": "royalblue"},
  {"id": "414", "group": "thirdfourth", "name": "Wengraf","color": "maroon"},
  {"id": "415", "group": "thirdfourth", "name": "Corby","color": "black"},
  {"id": "416", "group": "thirdfourth", "name": "Watson","color": "gray"},
  {"id": "417", "group": "thirdfourth", "name": "Wagener","color": "navy"},
  {"id": "51", "group": "fifthsixth", "name": "Pensinger", "color": "royalblue"},
  {"id": "52", "group": "fifthsixth", "name": "Drumm", "color": "teal"},
  {"id": "53", "group": "fifthsixth", "name": "Hudson/Price", "color": "skyblue"},
  {"id": "54", "group": "fifthsixth", "name": "Thornton", "color": "purple"},
  {"id": "55", "group": "fifthsixth", "name": "TJ Luchsen", "color": "grey"},
  {"id": "56", "group": "fifthsixth", "name": "Reisner/Huseby", "color": "royalblue"}
]
