module.exports = [
  {"id": "11","name": "Adair","color": "royalblue","contact": "Bill Adair"},
  {"id": "12","name": "Warth","color": "teal","contact": "Drew Warth"},
  {"id": "13","name": "DeVries/Walker","color": "pink","contact": "Adam DeVries/Ryan Walker"},
  {"id": "14","name": "Russ","color": "white","contact": "Ben Russ"},
  {"id": "15","name": "McGuigan","color": "gray","contact": "Joe Pat McGuigan"},
  {"id": "16","name": "Brandau","color": "navy","contact": "Alex Brandau"},
  {"id": "17","name": "Smith","color": "teal","contact": "Eric Smith"},
  {"id": "18","name": "Miller","color": "orange","contact": "Matt Miller"},
  {"id": "19","name": "Haraf/Murrel","color": "black","contact": "Frank Haraf/Nathan Murrel"},
  {"id": "110","name": "Stoddard","color": "green","contact": "Wes Stoddard"},
  {"id": "111","name": "Dacus","color": "lime","contact": "Ryan Dacus"},
  {"id": "112","name": "Frericks","color": "white","contact": "Ashley Frericks"},
  {"id": "113","name": "Brunner/Brackman","color": "lime","contact": "L. Brunner/A. Brackman"},
  {"id": "114","name": "Vernier/Laskaris","color": "yellow","contact": "Emy Vernier/M. Laskaris"},
  {"id": "115","name": "Skipper/Wooten/Rich","color": "green","contact": "H. Skipper/J. Wooten/J. Rich"},
  {"id": "116","name": "Barrett","color": "skyblue","contact": "Jack Barrett"},
  {"id": "117","name": "The Rathe's","color": "purple","contact": "Grant and Amanda Rathe"},
  {"id": "118","name": "Schultz","color": "red","contact": "Josh Schultz"},
  {"id": "21","name": "Nichols","color": "orange","contact": "Tim Nichols"},
  {"id": "22","name": "Duckworth","color": "maroon","contact": "Melissa Duckworth"},
  {"id": "23","name": "Spaeth","color": "white","contact": "Jason Spaeth"},
  {"id": "24","name": "Damp","color": "gray","contact": "Julia Damp"},
  {"id": "25","name": "Arthur","color": "navy","contact": "Scott Arthur"},
  {"id": "26","name": "Rivera","color": "green","contact": "Gaston Rivera"},
  {"id": "27","name": "Luedtke/Weaver","color": "black","contact": "R. Luedtke/C. Weaver"},
  {"id": "28","name": "Davis","color": "royalblue","contact": "Berkley Davis"},
  {"id": "29","name": "Beaird/DeVries","color": "red","contact": "Ryan Beaird/Adam DeVries"},
  {"id": "210","name": "Campos","color": "skyblue","contact": "Fabian Campos"},
  {"id": "211","name": "Little/Theobald","color": "maroon","contact": "Amanda Little/R. Theobald"},
  {"id": "212","name": "Austin","color": "teal","contact": "Eric Austin"},
  {"id": "213","name": "McGuire","color": "royalblue","contact": "Rob McGuire"},
  {"id": "214","name": "Sharpe","color": "purple","contact": "Josh Sharpe"},
  {"id": "215","name": "Holstein","color": "lime","contact": "Chris Holstein"},
  {"id": "216","name": "Cowles","color": "orange","contact": "Kevin Cowles"},
  {"id": "217","name": "Gaylon","color": "pink","contact": "Martha Gaylon"},
  {"id": "218","name": "Bryson","color": "skyblue","contact": "Adam Bryson"},
  {"id": "31", "name": "Edwards", "color": "pink", "contact": "Derek Edwards"},
  {"id": "32", "name": "Porter", "color": "white", "contact": "Drake Porter"},
  {"id": "33", "name": "Porter", "color": "pink", "contact": "Drake Porter"},
  {"id": "34", "name": "Gaither", "color": "white", "contact": "Mark Gaither"},
  {"id": "35", "name": "King", "color": "skyblue", "contact": "Tim King "},
  {"id": "36", "name": "Schultz/Lott", "color": "red", "contact": "Josh Schultz/Kris Lott"},
  {"id": "37", "name": "Thorton", "color": "gray", "contact": "Jim Thorton"},
  {"id": "38", "name": "Cherry", "color": "purple", "contact": "Leslie Cherry"},
  {"id": "39", "name": "Thurman", "color": "lime", "contact": "Patrick Thurman"},
  {"id": "310", "name": "Welborn", "color": "green", "contact": "Joe Welborn"},
  {"id": "311", "name": "Burton", "color": "yellow", "contact": "Jamie Burton"},
  {"id": "312", "name": "Milek/Meier", "color": "purple", "contact": "Jason Milek/Shad Meier"},
  {"id": "313", "name": "Ricciardelli", "color": "teal", "contact": "Nancy Ricciardelli"},
  {"id": "314", "name": "Mitchell", "color": "skyblue", "contact": "Chris Mitchell"},
  {"id": "315", "name": "Frost", "color": "yellow", "contact": "Jason Frost"},
  {"id": "316", "name": "McDaniel", "color": "black", "contact": "Thomas McDaniel"},
  {"id": "317", "name": "Hauser", "color": "maroon", "contact": "Laura Hauser"},
  {"id": "318", "name": "Franke", "color": "navy", "contact": "Robert Franke"},
  {"id": "319", "name": "Spengler", "color": "royalblue", "contact": "Craig Spengler"},
  {"id": "320", "name": "Peebles", "color": "lime", "contact": "Sam Peebles"},
  {"id": "41", "name": "Cedano","color": "black", "contact": "Anthony Cedano"},
  {"id": "42", "name": "Jacobs","color": "gray", "contact": "Robert Jacobs"},
  {"id": "43", "name": "M.Smith","color": "orange", "contact": "Mike Smith"},
  {"id": "44", "name": "Hagan","color": "navy", "contact": "Kevin Hagan"},
  {"id": "45", "name": "Perry","color": "royalblue", "contact": "Jim Perry "},
  {"id": "46", "name": "C.Smith","color": "white", "contact": "Christy Smith"},
  {"id": "47", "name": "Burton","color": "yellow", "contact": "Jamie Burton"},
  {"id": "48", "name": "Mitchell","color": "skyblue", "contact": "Chris Mitchell"},
  {"id": "49", "name": "Cooper","color": "teal", "contact": "Graham Cooper"},
  {"id": "410", "name": "Laufer","color": "navy", "contact": "Spencer Laufer"},
  {"id": "411", "name": "Ashworth/Martin","color": "skyblue", "contact": "K. Ashworth/M. Martin"},
  {"id": "412", "name": "Nicholson","color": "red", "contact": "Ryan Nicholson"},
  {"id": "413", "name": "Price","color": "pink", "contact": "Sterling Price"},
  {"id": "414", "name": "Pensinger","color": "royalblue", "contact": "Sharon Pensinger"},
  {"id": "415", "name": "Andreades","color": "gray", "contact": "Haley Andreades"},
  {"id": "51", "name": "Drumm", "color": "green", "contact": "Shannon Drumm"},
  {"id": "52", "name": "Thorton", "color": "purple", "contact": "Jim Thorton"},
  {"id": "53", "name": "Lawrence", "color": "maroon", "contact": "liz Lawrence"},
  {"id": "54", "name": "Johnston", "color": "lime", "contact": "Will Johnston"},
  {"id": "55", "name": "Blackburn", "color": "navy", "contact": "Mike Blackburn "},
  {"id": "56", "name": "Marmolejo", "color": "white", "contact": "David Marmolejo"},
  {"id": "57", "name": "Cotterman", "color": "teal", "contact": "Shelly Cotterman"},
  {"id": "58", "name": "Clark", "color": "red", "contact": "Chip Clark"}
]
